export const AU_CITIES: Record<string, string[]> = {
  NSW: [
    "Sydney",
    "Parramatta",
    "Newcastle",
    "Wollongong",
    "Penrith",
    "Liverpool",
    "Blacktown",
    "Canterbury-Bankstown",
    "Central Coast",
    "Wagga Wagga",
    "Albury",
    "Coffs Harbour",
    "Other",
  ],
  VIC: [
    "Melbourne",
    "Geelong",
    "Ballarat",
    "Bendigo",
    "Dandenong",
    "Sunshine",
    "Broadmeadows",
    "Point Cook",
    "Werribee",
    "Shepparton",
    "Other",
  ],
  QLD: [
    "Brisbane",
    "Gold Coast",
    "Sunshine Coast",
    "Logan",
    "Ipswich",
    "Townsville",
    "Cairns",
    "Toowoomba",
    "Other",
  ],
  WA: [
    "Perth",
    "Mandurah",
    "Bunbury",
    "Rockingham",
    "Joondalup",
    "Armadale",
    "Other",
  ],
  SA: ["Adelaide", "Salisbury", "Playford", "Marion", "Port Adelaide", "Other"],
  TAS: ["Hobart", "Launceston", "Devonport", "Burnie", "Other"],
  ACT: ["Canberra", "Other"],
  NT: ["Darwin", "Alice Springs", "Palmerston", "Other"],
};
